package api

import _ "embed"

// OpenAPIJSON is the embedded OpenAPI 3.1 document for the bcc API.
// It is regenerated by `make api-openapi` (which runs the
// internal/api/cmd/gen-openapi command) and committed to the repo so
// `go build` succeeds on a fresh clone before anyone runs the
// generator. Adapters in P3 will serve this byte slice from
// /api/v1/openapi.json directly.
//
//go:embed openapi.json
var OpenAPIJSON []byte
