package agentcontract

// Provider identifies which agent vendor produced a usage record. Adapters
// stamp this when they normalize the upstream stream into TokenUsage so
// downstream consumers can interpret the buckets correctly (the Anthropic
// adapter splits cache_read off input_tokens; OpenAI/Gemini adapters
// subtract cached_tokens out of prompt_tokens to keep buckets disjoint).
type Provider string

const (
	ProviderUnknown   Provider = ""
	ProviderAnthropic Provider = "anthropic"
	ProviderOpenAI    Provider = "openai"
	ProviderGoogle    Provider = "google"
)

// TokenUsage is the vendor-neutral, additive token-usage value object
// shared across all agent providers. The five buckets are disjoint by
// construction: each token a provider bills for lands in exactly one of
// them after the adapter's normalization, so Total() is meaningful
// regardless of vendor.
//
// Bucket semantics:
//   - InputFresh: prompt tokens computed from scratch on this call.
//   - InputCached: prompt tokens served from prefix cache (cheaper).
//   - CacheWrite: prompt tokens written to cache for later reuse (only
//     Anthropic exposes this as a separate billable bucket today; zero
//     for providers that fold it into the input price).
//   - Output: visible response tokens generated by the model.
//   - Reasoning: hidden thinking/reasoning tokens (o1/o3, Claude extended
//     thinking, Gemini 2.5 thoughts). Billed as output but tracked apart
//     so the caller can see what fraction of "output" was hidden.
//
// USD is reported by the provider on terminal events and is NOT held
// here so this type stays purely about token counts; cost is carried on
// the event envelope alongside TokenUsage.
type TokenUsage struct {
	InputFresh  int64 `json:"input_fresh"`
	InputCached int64 `json:"input_cached"`
	CacheWrite  int64 `json:"cache_write"`
	Output      int64 `json:"output"`
	Reasoning   int64 `json:"reasoning"`

	Provider Provider `json:"provider,omitempty"`
}

// Total returns the sum of all five buckets. This is the headline number
// surfaces (TUI, WebUI, sessions sidebar) display when they have room
// for one figure only. Disaggregation belongs in popovers and tables.
func (u TokenUsage) Total() int64 {
	return u.InputFresh + u.InputCached + u.CacheWrite + u.Output + u.Reasoning
}

// IsZero reports whether every bucket is zero. Used by emitters to
// decide whether to attach a usage payload to a wire event.
func (u TokenUsage) IsZero() bool {
	return u.InputFresh == 0 && u.InputCached == 0 && u.CacheWrite == 0 &&
		u.Output == 0 && u.Reasoning == 0
}

// Add returns the bucket-wise sum of u and v. The Provider tag of u
// wins; mixing providers in an aggregate is allowed but the resulting
// Provider should be treated as informational only by consumers.
func (u TokenUsage) Add(v TokenUsage) TokenUsage {
	u.InputFresh += v.InputFresh
	u.InputCached += v.InputCached
	u.CacheWrite += v.CacheWrite
	u.Output += v.Output
	u.Reasoning += v.Reasoning
	return u
}
