package spawnkit

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/fgmacedo/buchecha/internal/loop"
	"github.com/fgmacedo/buchecha/internal/provider"
	"github.com/fgmacedo/buchecha/internal/supervision/session"
)

// SpawnInfo carries the per-spawn metadata used by EmitSpawnStarted and
// EmitSpawnFinished. All fields are optional; zero values produce valid
// (though sparse) events.
type SpawnInfo struct {
	// Role is the cognitive role for this spawn (e.g. "bcc-executor").
	Role string
	// AgentID is the per-spawn registry id.
	AgentID string
	// PhaseID is the phase the spawn belongs to. Empty for the Planner.
	PhaseID string
	// IterationID is the briefing iteration id. Empty for the Planner.
	IterationID string
	// Attempt is the 1-based retry counter within the phase iteration.
	Attempt int
	// Provider is the vendor name (e.g. "claude", "codex").
	Provider string
	// Model is the model identifier passed to the agent.
	Model string
	// Effort is the effort/reasoning level passed to the agent.
	Effort string
	// SpawnID is the identifier generated by the adapter, used as the
	// basename of the prompt file under <sessionDir>/spawns/.
	SpawnID string
}

// PersistPrompt writes prompt to <store.SpawnsDir()>/<spawnID>.md with
// mode 0o600. The spawns directory is created on demand. It returns the
// absolute path of the written file.
func PersistPrompt(store *session.Store, spawnID, prompt string) (path string, err error) {
	if store == nil {
		return "", fmt.Errorf("spawnkit: PersistPrompt: nil store")
	}
	if spawnID == "" {
		return "", fmt.Errorf("spawnkit: PersistPrompt: empty spawnID")
	}
	promptPath := filepath.Join(store.SpawnsDir(), spawnID+".md")
	if mkdirErr := os.MkdirAll(filepath.Dir(promptPath), 0o755); mkdirErr != nil {
		return "", fmt.Errorf("spawnkit: PersistPrompt: mkdir: %w", mkdirErr)
	}
	if writeErr := os.WriteFile(promptPath, []byte(prompt), 0o600); writeErr != nil {
		return "", fmt.Errorf("spawnkit: PersistPrompt: write: %w", writeErr)
	}
	abs, absErr := filepath.Abs(promptPath)
	if absErr != nil {
		abs = promptPath
	}
	return abs, nil
}

// EmitSpawnStarted sends a loop.SpawnStarted event on events. The send is
// non-blocking: if the channel is full the event is silently dropped so
// the adapter never stalls the subprocess start waiting on a slow
// consumer. events may be nil, in which case EmitSpawnStarted is a no-op.
func EmitSpawnStarted(events chan<- loop.Event, info SpawnInfo, promptPath string, at time.Time) {
	if events == nil {
		return
	}
	select {
	case events <- loop.SpawnStarted{
		SpawnID:     info.SpawnID,
		Role:        info.Role,
		PhaseID:     info.PhaseID,
		IterationID: info.IterationID,
		Attempt:     info.Attempt,
		Provider:    info.Provider,
		Model:       info.Model,
		Effort:      info.Effort,
		PromptPath:  promptPath,
		At:          at,
	}:
	default:
	}
}

// EmitSpawnFinished sends a loop.SpawnFinished event on events.
// Like EmitSpawnStarted, the send is non-blocking.
// events may be nil, in which case EmitSpawnFinished is a no-op.
func EmitSpawnFinished(events chan<- loop.Event, info SpawnInfo, result provider.SpawnResult, at time.Time) {
	if events == nil {
		return
	}
	select {
	case events <- loop.SpawnFinished{
		SpawnID:    info.SpawnID,
		Role:       info.Role,
		ExitCode:   result.ExitCode,
		DurationMS: result.DurationMS,
		Cost: loop.SpawnCost{
			Tokens: result.Tokens,
			USD:    result.CostUSD,
		},
		At: at,
	}:
	default:
	}
}
