package handlers_test

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"

	"github.com/fgmacedo/buchecha/internal/api"
)

// TestOpenAPI_ServesEmbeddedBytesVerbatim asserts the openapi.json
// passthrough hands the request the exact bytes the //go:embed
// directive captured at build time. A regression here would mean a
// reformatted document on the wire vs. on disk, drifting clients
// from the contract regenerated by `make api-openapi`.
func TestOpenAPI_ServesEmbeddedBytesVerbatim(t *testing.T) {
	t.Parallel()

	srv := httptest.NewServer(api.New(nil).Routes())
	t.Cleanup(srv.Close)

	resp, err := http.Get(srv.URL + "/api/v1/openapi.json")
	if err != nil {
		t.Fatalf("get openapi.json: %v", err)
	}
	t.Cleanup(func() { _ = resp.Body.Close() })

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("status: got %d, want 200", resp.StatusCode)
	}
	if got := resp.Header.Get("Content-Type"); got != "application/json" {
		t.Errorf("content-type: got %q, want application/json", got)
	}
	if got := resp.Header.Get("Cache-Control"); got != "public, max-age=31536000, immutable" {
		t.Errorf("cache-control: got %q, want immutable", got)
	}
	if got, want := resp.Header.Get("Content-Length"), strconv.Itoa(len(api.OpenAPIJSON)); got != want {
		t.Errorf("content-length: got %q, want %q", got, want)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body: %v", err)
	}
	if !bytes.Equal(body, api.OpenAPIJSON) {
		t.Fatalf("body bytes do not match embedded OpenAPIJSON\nlen(body)=%d len(embed)=%d", len(body), len(api.OpenAPIJSON))
	}
}
